### PR TITLE
spwn: fallback to goods api for event info

### LINKED ISSUE #8: SPWN: Unable to fetch data.json on some events
https://spwn.jp/events/22052819-shigureui fails to retrieve `data.json` with a 404 error (same error in the browser), so the plugin doesn't work, but I can stream the event in the browser.

### PR DESCRIPTION
**Pull request by pmrowla**
- fall back to goods API when `data.json` is unavailable
- does not address potential case where we get a multi-part event with 404 `data.json`

may fix https://github.com/pmrowla/streamlink-plugins/issues/8

### CODE REVIEW

**Comment by pmrowla** [comment]
@ephemient can you try this PR and see if it works for you

**Comment by ephemient** [comment]
It gets further, but still dies:
```
$ streamlink -l trace https://spwn.jp/events/22052819-shigureui
[02:56:16.765404][session][info] Resolved plugin spwn with deprecated can_handle_url API
[02:56:16.766787][cli][debug] OS:         Linux-5.15.0-30-generic-x86_64-with-glibc2.35
[02:56:16.766852][cli][debug] Python:     3.10.4
[02:56:16.766891][cli][debug] Streamlink: 4.1.0
[02:56:16.766923][cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[02:56:16.767036][cli][debug] Arguments:
[02:56:16.767072][cli][debug]  url=https://spwn.jp/events/22052819-shigureui
[02:56:16.767110][cli][debug]  --loglevel=trace
[02:56:16.767182][cli][debug]  --spwn-token=********
[02:56:17.033475][cli][info] Found matching plugin spwn for URL https://spwn.jp/events/22052819-shigureui
[02:56:17.821575][plugins.spwn][info] Found SPWN event: うい・おん・すてーじ　－雨上がりの文化祭－
[02:56:18.544325][utils.l10n][debug] Language code: en_US
[02:56:18.700883][plugins.spwn][debug] The stream 'うい・おん・すてーじ　－雨上がりの文化祭－_144p' has been ignored since it is badly named.
[02:56:18.701023][plugins.spwn][debug] The stream 'うい・おん・すてーじ　－雨上がりの文化祭－_240p' has been ignored since it is badly named.
[02:56:18.701103][plugins.spwn][debug] The stream 'うい・おん・すてーじ　－雨上がりの文化祭－_360p' has been ignored since it is badly named.
[02:56:18.701171][plugins.spwn][debug] The stream 'うい・おん・すてーじ　－雨上がりの文化祭－_480p' has been ignored since it is badly named.
[02:56:18.701233][plugins.spwn][debug] The stream 'うい・おん・すてーじ　－雨上がりの文化祭－_720p' has been ignored since it is badly named.
[02:56:18.701293][plugins.spwn][debug] The stream 'うい・おん・すてーじ　－雨上がりの文化祭－_1080p' has been ignored since it is badly named.
error: No playable streams found on this URL: https://spwn.jp/events/22052819-shigureui
```

As a workaround,
```diff
diff --git a/spwn.py b/spwn.py
index 4f30ec1..0054367 100644
--- a/spwn.py
+++ b/spwn.py
@@ -310,7 +310,7 @@ class Spwn(Plugin):
                 continue
             yield VideoPart(
                 video_id,
-                name.replace(" ", "_").lower(),
+                video_id.replace(" ", "_").lower(),
                 url,
                 default_cookie.get("cookie", {})
             )
```
gets past that and everything works successfully from there on. But there's probably better value to put there, I just haven't checked where that data flows.

**Comment by pmrowla** [comment]
@ephemient please try the latest version (it should generate stream qualities without any title/prefix, just the resolution)

**Review by ephemient — APPROVED** [review]
Yes, this seems to work for me.

**Pull request merged**
