### PR TITLE
eplus: support account; refresh cookies within 15 mins; check "drm_mode"

### PR DESCRIPTION
**Pull request by pzhlkj6612**
## Test

Cookie:

```
[cli][debug] Arguments:
[cli][debug]  url=https://live.eplus.jp/1111111
[cli][debug]  stream=['worst']
[cli][debug]  --http-cookie=[('ci_session', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')]
[cli][info] Found matching plugin eplus for URL https://live.eplus.jp/1111111
[plugins.eplus.Eplus][info] Getting auth status
[plugins.eplus][debug] delivery_status = CONFIRMED_ARCHIVE, archive_mode = ON
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)

```

ID and password:

```
[cli][debug] Arguments:
[cli][debug]  url=https://live.eplus.jp/1111111
[cli][debug]  stream=['worst']
[cli][debug]  --eplus-id=********
[cli][debug]  --eplus-password=********
[cli][info] Found matching plugin eplus for URL https://live.eplus.jp/1111111
[plugins.eplus.Eplus][info] Getting auth status
[plugins.eplus.Eplus][info] Sending pre-login info
[plugins.eplus.Eplus][info] Logging in via provided id and password
[plugins.eplus][debug] delivery_status = CONFIRMED_ARCHIVE, archive_mode = ON
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)

```

Please help me re-phrase the docs. :-)

### CODE REVIEW

**Comment by pmrowla** [comment]
Thanks for the PR, it looks good at a quick glance but I probably won't be able to do a real review and testing it for a couple of weeks (I'm in Japan for ijigen fes and the yohane live and don't have a computer with me)

**Comment by pzhlkj6612** [comment]
> ijigen fes and the yohane live

Oh, have a nice vacation!!!

**Comment by pzhlkj6612** [comment]
Refreshing the session by accessing `https://live.eplus.jp/api/stream/{app_id}/status?sid={stream_session}` sometimes doesn't work for inbound URLs, so I kept the branch about `session_update_url` there.

**Comment by pzhlkj6612** [comment]
Unfortunately, the logged-in session will be invalidated by another login. We may have to make our SessionUpdater perform login for eplus.jp account.

**Comment by pzhlkj6612** [comment]
I did it! See 8a3a4655e0cfa11a3b04223a99c7a5c1d1cfc691 .

```
...

[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/{app_id}/status?sid={old_stream_session}
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: ...
[debug] Found a valid cookie that will expire at ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshed cookies. Next attempt will be at about ...

...

Oops, you opened the player webpage!

...

[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/{app_id}/status?sid={old_stream_session}
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: ...
[error] No valid cookies found.
[plugins.eplus][info] Getting auth status
[plugins.eplus][info] Sending pre-login info
[plugins.eplus][info] Logging in via provided id and password
[plugins.eplus.EplusSessionUpdater][debug] We will retry in 1s.
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/{app_id}/status?sid={new_stream_session}
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: ...
[debug] Found a valid cookie that will expire at ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshed cookies. Next attempt will be at about ...

...

You quickly closed the web browser.

...

[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/{app_id}/status?sid={old_stream_session}
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: ...
[debug] Found a valid cookie that will expire at ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshed cookies. Next attempt will be at about ...

```

**Comment by pmrowla** [comment]
Sorry for the delay, I did a quick test w/my eplus account and it looks like everything works, but I do want to discuss this:

> Unfortunately, the logged-in session will be invalidated by another login. We may have to make our SessionUpdater perform login for eplus.jp account.

> I did it! See https://github.com/pmrowla/streamlink-plugins/commit/8a3a4655e0cfa11a3b04223a99c7a5c1d1cfc691

I'm not sure the session updater should login. This will disable playback on the newly logged in web session, right? I'd prefer that the plugin behave the same as a web browser, where you can only watch on the most recently logged in session (so using the plugin after the new web login would require the user restarting streamlink to force a fresh plugin login).

**Comment by pzhlkj6612** [comment]
Thanks for your reply!

> This will disable playback on the newly logged in web session, right? 

Right. The web session will be interrupted by "device number limit".

> I'd prefer that the plugin behave the same as a web browser, where you can only watch on the most recently logged in session (so using the plugin after the new web login would require the user restarting streamlink to force a fresh plugin login).

Well, if so, the behavior between "inbound eplus links" and "japan eplus links" will become different. That is, if we use the code in the "master" branch, for inbound links, each cookie refreshing action performed by the session updater will interrupt the web session by "device number limit". An "inbound eplus link" **equals** a "japan eplus link" with login credential. A reloading of an inbound link in web browser **equals** opening a japan link and logging it in.

In addition, I think we may have a way to check if an inbound link has been opened by another session (web browser or another streamlink).

Now I feel a bit dumb: What features should we implement? Does the old code need to be modified as well?

**Comment by pmrowla** [comment]
> Thanks for your reply!

> Well, if so, the behavior between "inbound eplus links" and "japan eplus links" will become different. That is, if we use the code in the "master" branch, for inbound links, each cookie refreshing action performed by the session updater will interrupt the web session by "device number limit". An "inbound eplus link" **equals** a "japan eplus link" with login credential. A reloading of an inbound link in web browser **equals** opening a japan link and logging it in.
> 
> Now I feel a bit dumb: What features should we implement? Does the old code need to be modified as well?

For the inbound/international links we should really be refreshing the existing session cookie instead of clearing all cookies and then obtaining a new one, but this was never really an issue worth fixing until now (afaik the last time I tried it eplus didn't actually boot me from a browser viewing session if I also opened the stream in streamlink)

This also applies for the domestic/jp version. Since we are doing an actual login now, we should be caching the login session cookie (using the existing streamlink behavior for caching logins) and not doing a completely new login each time. Basically, I shouldn't be getting repeated "new login from ..." eplus emails every time the plugin needs to refresh the session.

You can leave this PR alone for now, I'll probably just merge it as-is and then clean up the refresh behavior later.

**Comment by pzhlkj6612** [comment]
> we should be caching the login session cookie...

> ... Basically, I shouldn't be getting repeated "new login from ..." eplus emails every time the plugin needs to refresh the session.

I agree.

Now I'm going to find the answer to a question: **how do I know if a session has been invalidated?** If we can check it, we could make things more flexible. I mean, we could provide an option to control whether to kick the other session when updating session of streamlink.

> (afaik the last time I tried it eplus didn't actually boot me from a browser viewing session if I also opened the stream in streamlink)

I think you might be wrong. I always see "Due to excess of the limitation number of devices, this video is no longer available" after opening streamlink.

<br>

So, this PR should not be merged. I'll make things clearer, then make code better.

**Comment by pzhlkj6612** [comment]
Hi!

> Basically, I shouldn't be getting repeated "new login from ..." eplus emails every time the plugin needs to refresh the session.

Done. I think the current code is better than before.

**Comment by pzhlkj6612** [comment]
### For inbound/international eplus

If `--eplus-allow-relogin` was set (please note the retries):

```
...
[plugins.eplus.EplusSessionUpdater][debug] Starting session updater...
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=000
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][debug] Found a valid cookie that will expire at ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshed cookies. Next attempt will be at about ...
[stream.hls] ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=000
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][debug] Found a valid cookie that will expire at ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshed cookies. Next attempt will be at about ...
[stream.hls] ...

I opened the webpage.

[stream.hls] ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=000
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][error] No valid cookies found.
[plugins.eplus.EplusSessionUpdater][info] Trying to refresh the session. Any existing sessions will be kicked.
[plugins.eplus][info] Getting auth status
[plugins.eplus][debug] delivery_status = CONFIRMED_ARCHIVE, archive_mode = ON
[plugins.eplus.EplusSessionUpdater][debug] We will retry in 1s.
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=001
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][error] No valid cookies found.
[plugins.eplus.EplusSessionUpdater][info] Trying to refresh the session. Any existing sessions will be kicked.
[plugins.eplus][info] Getting auth status
[plugins.eplus][debug] delivery_status = CONFIRMED_ARCHIVE, archive_mode = ON
[plugins.eplus.EplusSessionUpdater][debug] We will retry in 2s.
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=002
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][debug] Found a valid cookie that will expire at ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshed cookies. Next attempt will be at about ...
[stream.hls] ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=002
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][debug] Found a valid cookie that will expire at ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshed cookies. Next attempt will be at about ...
[stream.hls] ...

Due to excess of the limitation number of devices, this video is no longer available.

...

```

If `--eplus-allow-relogin` was not set (please note the first re-login):

```
...
[plugins.eplus.EplusSessionUpdater][debug] Starting session updater...
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=000
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][error] No valid cookies found.
[plugins.eplus.EplusSessionUpdater][info] Trying to refresh the session. Any existing sessions will be kicked.
[plugins.eplus][info] Getting auth status
[cli][debug] Writing stream to output
[plugins.eplus][debug] delivery_status = CONFIRMED_ARCHIVE, archive_mode = ON
[plugins.eplus.EplusSessionUpdater][debug] We will retry in 1s.
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=001
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][debug] Found a valid cookie that will expire at ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshed cookies. Next attempt will be at about ...
[stream.hls] ...

I opened the webpage.

[stream.hls] ...
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=001
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][error] No valid cookies found.
[plugins.eplus.EplusSessionUpdater][info] The session will not be refreshed since re-login is disabled.
[plugins.eplus.EplusSessionUpdater][debug] We will retry in 1s.
[plugins.eplus.EplusSessionUpdater][debug] Refreshing cookies with url: https://live.eplus.jp/api/stream/.../status?sid=001
[plugins.eplus.EplusSessionUpdater][debug] Got new cookies: <...>
[plugins.eplus.EplusSessionUpdater][error] No valid cookies found.
[plugins.eplus.EplusSessionUpdater][info] The session will not be refreshed since re-login is disabled.
[plugins.eplus.EplusSessionUpdater][debug] We will retry in 2s.
[stream.hls] ...

The player on the webpage was working well.

...

```

.

**Comment by pmrowla** [comment]
Thanks for updating this, I'll try to get to this review over the weekend

**Comment by pzhlkj6612** [comment]
Hi, @pmrowla! I've been using some new functions of the Streamlink, so we should do compatibility test before merging this PR (possible README updates). I'll test it first in a few days.

**Comment by pzhlkj6612** [comment]
> I'll test it first in a few days.

Done. We need Python 3.8 and Streamlink 5.5.0.

**Comment by pzhlkj6612** [comment]
10c3c5d7727326db624a50e360eef5fce567c8cd:

```diff
- [cli][debug]  --eplus-password=42
+ [cli][debug]  --eplus-password=********

```

.

**Comment by pzhlkj6612** [comment]
52a8529879e8f528ebe6a67c95a1b3372da45ab9:

```diff
- [cli][debug]  --eplus-id=42
+ [cli][debug]  --eplus-id=********

```

Don't leak my phone number!

**Pull request merged**
